---
base_image: ubuntu:26.04

labels:
  maintainer: "Maciej Rachuna <rachuna.maciej@gmail.com>"
  image_source: "https://gitlab.com/dev.rachuna/artifacts/containers/conftest"

env:
  DEBIAN_FRONTEND: noninteractive
  TF_IN_AUTOMATION: "true"
  LANG: C.UTF-8

before_build_commands:
  ## add execute permissions to scripts
  - chmod +x bin/*

packages:
  - bash
  - curl
  - git
  - gnupg2
  - jq
  - libssl3
  - openssh-client
  - ca-certificates

custom_repos: []

copy:
  - source: bin
    destination: /tmp/bin

extra_commands:
  - find /tmp/bin -maxdepth 1 -type f -executable -exec {} \;

user:
  name: nonroot
  shell: /bin/bash
  home: /home/nonroot
  uid: 10000

entrypoint: null
cmd: "/bin/bash"
