---
base_image: ubuntu:26.04

labels:
  maintainer: "Maciej Rachuna <rachuna.maciej@gmail.com>"
  image_source: "https://gitlab.com/dev.rachuna/artifacts/containers/conftest"

env:
  DEBIAN_FRONTEND: noninteractive
  TF_IN_AUTOMATION: "true"
  LANG: C.UTF-8

before_build_commands:
  ## contest
  - curl -sLo ./conftest.tar.gz https://github.com/open-policy-agent/conftest/releases/download/v0.68.2/conftest_0.68.2_Linux_x86_64.tar.gz
  - tar xzf conftest.tar.gz
  ## removal of default user 'ubuntu'
  - chmod +x bin/removal_default_user

packages:
  - bash
  - curl
  - git
  - gnupg2
  - jq
  - libssl3
  - openssh-client
  - ca-certificates

custom_repos: []

extra_commands:
  - ./tmp/removal_default_user
  - conftest --version

copy:
  - source: conftest
    destination: /usr/local/bin/conftest
  - source: bin/removal_default_user
    destination: /tmp/removal_default_user

user:
  name: nonroot
  shell: /bin/bash
  home: /home/nonroot
  uid: 10000

entrypoint: null
cmd: "/bin/bash"
